# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "3"

services:
  todo-redis:
    container_name: todo-redis
    image: redis:5.0.3
    ports:
      - 6379:6379

  todo-postgres:
    container_name: todo-postgres
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTFRES_USER=todo
      - POSTGRES_PASSWORD=todo123
      - POSTGRES_DB=todo

  todo-elastic:
    container_name: todo-elastic
    image: elasticsearch:6.6.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  todo-api:
    container_name: todo-api
    image: todo-api:1.0
    ports:
      - 300:3000
    environment:
      - POSTGRES_HOST=todo-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo123
      - POSTGRES_DATABASE=todo
      - REDIS_HOST=todo-redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=todo-elastic
      - ELASTICSEARCH_PORT=9200
    volumes:
      - /app/node_modules
    depends_on:
      - todo_redis
      - todo-postgres
      - todo-elastic
  todo-view:
    container_name: todo-view
    image: todo-view:1.0
    ports:
      - 4200:4200
    volumes:
      - ${PWD}/todo-view:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - todo-api

  todo-proxy:
    container_name: todo-proxy
    image: todo-proxy:1.0
    ports:
      - 8080:8080
    depends_on:
      - todo-api
      - todo-view
